// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScraperTool.Data;

#nullable disable

namespace ScraperTool.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630_AddInvestigationMetadataEntities")]
    partial class AddInvestigationMetadataEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ScraperTool.Data.Entities.FieldDefinitionEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("DisplayOrder")
                    .HasColumnType("INTEGER");

                b.Property<string>("FieldName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ExpectedCharacteristics")
                    .HasColumnType("TEXT");

                b.Property<string>("NotExpected")
                    .HasColumnType("TEXT");

                b.Property<string>("Purpose")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("FieldName")
                    .IsUnique();

                b.ToTable("FieldDefinitions");
            });

            modelBuilder.Entity("ScraperTool.Data.Entities.InvestigationWorkflowEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("IsRequired")
                    .HasColumnType("INTEGER");

                b.Property<int>("StepNumber")
                    .HasColumnType("INTEGER");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("StepNumber")
                    .IsUnique();

                b.ToTable("InvestigationWorkflows");
            });

            modelBuilder.Entity("ScraperTool.Data.Entities.DecisionGuidelineEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("FieldName")
                    .HasColumnType("TEXT");

                b.Property<string>("Guideline")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<bool>("IsEnabled")
                    .HasColumnType("INTEGER");

                b.Property<int>("Priority")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("Priority", "Id");

                b.ToTable("DecisionGuidelines");
            });
#pragma warning restore 612, 618
        }
    }
}